import{useEffect,useState}from"react";
import PageHeader from"../../components/PageHeader";
import Modal from"../../components/Modal";
import{createEmployee,getEmployees,updateEmployee,updateEmployeePassword}from"../../controllers/operationsController";

const roles={owner:"Propietario",admin:"Administrador",waiter:"Mesero",cashier:"Caja",kitchen:"Cocina / comandas",auditor:"Auditor"};
export default function EmployeesPage(){
 const[open,setOpen]=useState(false),[editing,setEditing]=useState(null),[people,setPeople]=useState([]),[error,setError]=useState(""),[message,setMessage]=useState("");
 const load=()=>getEmployees().then(setPeople).catch(e=>setError(e.message));useEffect(()=>{load()},[]);
 const add=async e=>{e.preventDefault();const f=new FormData(e.currentTarget);try{await createEmployee({displayName:f.get("name"),username:f.get("username"),password:f.get("password"),role:f.get("role")});setOpen(false);setMessage("Usuario creado. Ya puede iniciar sesión desde otro dispositivo.");load()}catch(e){setError(e.message)}};
 const save=async e=>{e.preventDefault();const f=new FormData(e.currentTarget),password=f.get("password");try{await updateEmployee(editing.id,{role:f.get("role"),status:f.get("status")});if(password)await updateEmployeePassword(editing.id,password);setEditing(null);setMessage(password?"Acceso y contraseña actualizados":"Acceso actualizado");load()}catch(e){setError(e.message)}};
 return <div className="content"><PageHeader eyebrow="EQUIPO" title="Usuarios y estaciones" description="Crea accesos separados para administración, caja, meseros y cocina." action={<button className="primary-action" onClick={()=>setOpen(true)}>＋ Crear usuario</button>}/>{error&&<div className="form-alert module-alert">{error}</div>}{message&&<div className="success-alert module-alert">✓ {message}</div>}
  <section className="plan-notice"><div><strong>2 conexiones móviles incluidas</strong><p>Los accesos web de Caja y Cocina se controlan por separado según el plan.</p></div><span>Plan actual</span></section>
  <section className="surface-card table-surface"><div className="table-heading"><h2>Miembros del equipo</h2></div><div className="data-table"><div className="table-row table-labels"><span>Empleado</span><span>Rol</span><span>Estado</span><span>Estación inicial</span><span/></div>{people.map(p=><div className="table-row" key={p.id}><span><b>{p.profile?.display_name||"Sin nombre"}</b><small>{p.profile?.username||p.profile?.email}</small></span><span>{roles[p.role]||p.role}</span><span><i className={`dot ${p.status==="active"?"free":"occupied"}`}/>{p.status==="active"?"Activo":p.status==="suspended"?"Suspendido":"Invitado"}</span><span>{p.role==="cashier"?"Pedidos y caja":p.role==="kitchen"?"Panel de comandas":p.role==="waiter"?"Pedidos y mesas":"Panel administrativo"}</span><button className="secondary-button" onClick={()=>setEditing(p)}>Editar</button></div>)}</div></section>
  {open&&<Modal title="Crear usuario del restaurante" description="La persona podrá entrar inmediatamente con este usuario y contraseña inicial." onClose={()=>setOpen(false)}><form className="module-form" onSubmit={add}><label>Nombre<input name="name" required/></label><label>Usuario<input name="username" minLength="3" maxLength="30" pattern="[a-zA-Z0-9._-]+" autoCapitalize="none" required/><small>Letras, números, punto, guion o guion bajo.</small></label><label>Contraseña inicial<input name="password" type="password" minLength="8" required/><small>Mínimo 8 caracteres. Entrégala únicamente al empleado.</small></label><label>Rol<select name="role"><option value="cashier">Caja</option><option value="kitchen">Cocina / comandas</option><option value="waiter">Mesero</option><option value="admin">Administrador</option><option value="auditor">Auditor</option></select></label><button className="primary-action">Crear y asociar usuario</button></form></Modal>}
  {editing&&<Modal title={`Editar acceso · ${editing.profile?.display_name||"Usuario"}`} description={`Usuario de ingreso: ${editing.profile?.username||editing.profile?.email||"Sin usuario"}`} onClose={()=>setEditing(null)}><form className="module-form" onSubmit={save}><label>Rol<select name="role" defaultValue={editing.role}>{Object.entries(roles).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label><label>Estado<select name="status" defaultValue={editing.status}><option value="active">Activo</option><option value="suspended">Suspendido</option></select></label><label>Nueva contraseña (opcional)<input name="password" type="password" minLength="8" autoComplete="new-password" placeholder="Déjala vacía para conservarla"/><small>Por seguridad la contraseña actual no se puede consultar. Escribe una nueva solamente si necesitas restablecerla.</small></label><button className="primary-action">Guardar acceso</button></form></Modal>}
 </div>;
}
