import { useEffect, useState } from "react";
import PageHeader from "../../components/PageHeader";
import EmptyState from "../../components/EmptyState";
import LoadingState from "../../components/LoadingState";
import { getOrders, updateOrder } from "../../controllers/operationsController";

export default function KitchenPage() {
  const [orders, setOrders] = useState([]);
  const [error, setError] = useState("");
  const [loading, setLoading] = useState(true);
  const load = (silent = false) => { if (!silent) setLoading(true); return getOrders().then((data) => { const today=new Date().toDateString();const visible = data.filter((order) => !["paid", "cancelled", "refunded"].includes(order.status)&&(order.status!=="delivered"||new Date(order.updated_at).toDateString()===today)); setOrders(visible); window.dispatchEvent(new CustomEvent("orders:count", { detail: data.filter((order) => !["paid", "cancelled", "refunded"].includes(order.status)).length })); }).catch((failure) => setError(failure.message)).finally(() => { if (!silent) setLoading(false); }); };
  useEffect(() => { const refresh=()=>load(true);load();const timer=window.setInterval(refresh,15000);window.addEventListener("operations:changed",refresh);return()=>{window.clearInterval(timer);window.removeEventListener("operations:changed",refresh)}; }, []);
  const move = async (order, status) => { try { await updateOrder(order.id, { status }); await load(); } catch (failure) { setError(failure.message); } };
  const print = (order) => window.open(`/imprimir/pedido/${order.id}?tipo=comanda`, "_blank");
  const column = (status, title, next, nextLabel) => { const list = orders.filter((order) => order.status === status); return <div><h2>{title}<b>{list.length}</b></h2>{list.length ? list.map((order) => <article className="kitchen-ticket" key={order.id}><div><strong>Pedido #{order.order_number}</strong><small>{order.dining_tables?.name || order.customer_name || "Cliente"}</small></div><div className="kitchen-ticket-items">{(order.order_items || []).map((item) => <p key={item.id}><b>{Number(item.quantity)}×</b><span>{item.product_name}{(item.selections||[]).map(selection=><small key={selection.optionId}>{selection.group}: {selection.name}</small>)}{item.notes && <small>{item.notes}</small>}</span></p>)}</div>{order.notes && <div className="kitchen-card-note"><b>Observación</b><span>{order.notes}</span></div>}<div className="ticket-actions"><button className="ticket-print" onClick={() => print(order)}>Imprimir comanda</button>{next && <button onClick={() => move(order, next)}>{nextLabel} →</button>}</div></article>) : <EmptyState icon="CO" title="Sin pedidos" description="La cocina está al día." />}</div>; };
  if (loading) return <div className="content kitchen-content"><PageHeader eyebrow="PRODUCCIÓN" title="Cocina" description="Pedidos organizados por estado y prioridad." /><section className="surface-card"><LoadingState label="Sincronizando pedidos de cocina..." /></section></div>;
  return <div className="content kitchen-content"><PageHeader eyebrow="PRODUCCIÓN" title="Cocina" description="Pedidos organizados por estado y prioridad." />{error && <div className="form-alert module-alert">{error}</div>}<div className="kitchen-summary"><span><b>{orders.filter((order) => order.status === "new").length}</b> nuevos</span><span><b>{orders.filter((order) => order.status === "preparing").length}</b> preparando</span><span><b>{orders.filter((order) => order.status === "ready").length}</b> listos</span><span><b>{orders.filter((order) => order.status === "delivered").length}</b> entregados</span></div><section className="kitchen-board kitchen-board-four">{column("new", "Nuevos", "preparing", "Preparar")}{column("preparing", "En preparación", "ready", "Marcar listo")}{column("ready", "Listos", "delivered", "Entregar")}{column("delivered", "Entregados", null, null)}</section></div>;
}
