import { useEffect, useState } from "react";
import { Link } from "react-router-dom";
import LoadingState from "../../components/LoadingState";
import { getCash, getOrders, getReportSummary } from "../../controllers/operationsController";

export default function DashboardPage() {
  const [data, setData] = useState({ sales: 0, orders: 0, average: 0 });
  const [cash, setCash] = useState(null);
  const [preparing, setPreparing] = useState(0);
  const [error, setError] = useState("");
  const [loading, setLoading] = useState(true);
  useEffect(() => { let active = true; setLoading(true); Promise.all([getReportSummary(), getCash(), getOrders()]).then(([summary, cashData, orders]) => { if (!active) return; setData(summary); setCash(cashData.session); setPreparing(orders.filter((order) => order.status === "preparing").length); window.dispatchEvent(new CustomEvent("orders:count", { detail: orders.filter((order) => !["paid", "cancelled", "refunded"].includes(order.status)).length })); }).catch((failure) => { if (active) setError(failure.message); }).finally(() => { if (active) setLoading(false); }); return () => { active = false; }; }, []);
  const money = (number) => `$${Number(number || 0).toLocaleString("es-CO")}`;
  return <div className="content"><section className="welcome-row"><div><span className="date-label">RESUMEN ACTUAL</span><h1>Buenas tardes, Administrador</h1><p>Información registrada en tu restaurante.</p></div><Link className="primary-action" to="/pedidos"><span>＋</span> Nuevo pedido</Link></section>{error && <div className="form-alert module-alert">{error}</div>}{loading ? <section className="surface-card"><LoadingState label="Preparando el resumen del restaurante..." /></section> : <><section className="metrics-grid"><article className="metric-card featured"><div className="metric-head"><span>Ventas registradas</span><span className="trend neutral">Actual</span></div><strong>{money(data.sales)}</strong><small>{data.orders ? "Información actualizada" : "Aún no hay ventas registradas"}</small></article><article className="metric-card"><div className="metric-head"><span>Pedidos pagados</span><span className="metric-symbol amber">01</span></div><strong>{data.orders}</strong><small>{preparing} en preparación</small><Link to="/pedidos">Ver pedidos <span>→</span></Link></article><article className="metric-card"><div className="metric-head"><span>Promedio por pedido</span><span className="metric-symbol sage">$</span></div><strong>{money(data.average)}</strong><small>Calculado con pedidos pagados</small><Link to="/informes">Ir a informes <span>→</span></Link></article><article className="metric-card"><div className="metric-head"><span>Estado de caja</span><span className="metric-symbol blue">CJ</span></div><strong className={cash ? "open-status" : "closed-status"}><span /> {cash ? "Abierta" : "Cerrada"}</strong><small>{cash ? `Base inicial: ${money(cash.opening_amount)}` : "Ábrela para iniciar operaciones"}</small><Link to="/caja">{cash ? "Ver caja" : "Abrir caja"} <span>→</span></Link></article></section><section className="activity-card"><div className="card-title-row compact"><div><span className="eyebrow">SIGUIENTE PASO</span><h2>{cash ? "Continúa con la operación" : "Abre la caja para comenzar el turno"}</h2></div></div><div className="empty-state"><span className="empty-icon">→</span><div><strong>{cash ? "Registra pedidos con productos" : "La caja aún está cerrada"}</strong><p>{cash ? "Los pedidos enviados aparecerán automáticamente en cocina." : "La apertura se reflejará aquí inmediatamente al regresar al dashboard."}</p></div><Link className="secondary-action" to={cash ? "/pedidos" : "/caja"}>{cash ? "Crear pedido" : "Ir a caja"}</Link></div></section></>}</div>;
}
