import { useEffect, useState } from "react";
import PageHeader from "../../components/PageHeader";
import EmptyState from "../../components/EmptyState";
import LoadingState from "../../components/LoadingState";
import { getReportSummary } from "../../controllers/operationsController";
import { getRestaurantProfile } from "../../controllers/authController";
import { downloadReportExcel, downloadReportPdf } from "../../utils/reportExport";

const today=()=>new Intl.DateTimeFormat("en-CA",{timeZone:"America/Bogota",year:"numeric",month:"2-digit",day:"2-digit"}).format(new Date());
const labels={table:"Mesa",takeaway:"Para llevar",delivery:"Domicilio"};

export default function ReportsPage(){
  const[period,setPeriod]=useState("day");const[date,setDate]=useState(today());const[data,setData]=useState({sales:0,refundTotal:0,foodSales:0,deliveryFees:0,packagingFees:0,paymentTotals:{cash:0,card:0,transfer:0},expenseTotal:0,orders:0,average:0,salesDetail:[],refundDetail:[],expenseDetail:[]});const[profile,setProfile]=useState(null);const[error,setError]=useState("");const[loading,setLoading]=useState(true);const[exporting,setExporting]=useState("");
  const load=()=>{setLoading(true);setError("");Promise.all([getReportSummary(period,date),getRestaurantProfile()]).then(([report,restaurantProfile])=>{setData(report);setProfile(restaurantProfile)}).catch(failure=>setError(failure.message)).finally(()=>setLoading(false))};useEffect(()=>{load()},[period,date]);
  const money=value=>`$${Number(value||0).toLocaleString("es-CO")}`;const formatDate=value=>new Date(value).toLocaleString("es-CO",{dateStyle:"short",timeStyle:"short"});
  const exportFile=async(type)=>{setExporting(type);setError("");try{const payload={data,profile,period,date};if(type==="excel")await downloadReportExcel(payload);else await downloadReportPdf(payload)}catch(failure){setError(`No fue posible generar el archivo: ${failure.message}`)}finally{setExporting("")}};
  if(loading)return <div className="content"><PageHeader eyebrow="ANÁLISIS" title="Informes" description="Consulta ventas y salidas con su detalle por periodo."/><section className="surface-card"><LoadingState label="Calculando ventas y salidas..."/></section></div>;
  return <div className="content report-print-area"><PageHeader eyebrow="ANÁLISIS" title="Informes" description="Consulta ventas y salidas con su detalle por periodo." action={<div className="report-export-actions"><button className="secondary-button" onClick={()=>exportFile("excel")} disabled={Boolean(exporting)}>{exporting==="excel"?"Generando Excel...":"Descargar Excel"}</button><button className="secondary-button" onClick={()=>exportFile("pdf")} disabled={Boolean(exporting)}>{exporting==="pdf"?"Generando PDF...":"Descargar PDF"}</button></div>}/>{error&&<div className="form-alert module-alert">{error}</div>}<div className="report-period-bar"><div className="segmented"><button className={period==="day"?"active":""} onClick={()=>setPeriod("day")}>Día</button><button className={period==="week"?"active":""} onClick={()=>setPeriod("week")}>Semana</button><button className={period==="month"?"active":""} onClick={()=>setPeriod("month")}>Mes</button></div><label>Fecha de referencia<input type="date" value={date} onChange={event=>setDate(event.target.value)}/></label><span>Datos actualizados</span></div>
    <section className="metrics-grid report-metrics"><article className="metric-card"><div className="metric-head"><span>Total de ventas</span></div><strong>{money(data.sales)}</strong><small>{data.orders} {data.orders===1?"pedido pagado":"pedidos pagados"}</small></article><article className="metric-card"><div className="metric-head"><span>Devoluciones</span></div><strong>{money(data.refundTotal)}</strong><small>{data.refundDetail?.length||0} {(data.refundDetail?.length||0)===1?"pedido devuelto":"pedidos devueltos"}</small></article><article className="metric-card"><div className="metric-head"><span>Total de salidas</span></div><strong>{money(data.expenseTotal)}</strong><small>{data.expenseDetail.length} {data.expenseDetail.length===1?"movimiento registrado":"movimientos registrados"}</small></article><article className="metric-card"><div className="metric-head"><span>Domicilios y empaques</span></div><strong>{money(Number(data.deliveryFees)+Number(data.packagingFees))}</strong><small>Incluidos en las ventas</small></article></section>
    <div className="payment-breakdown"><span><b>Efectivo</b> {money(data.paymentTotals?.cash)}</span><span><b>Tarjeta</b> {money(data.paymentTotals?.card)}</span><span><b>Transferencia</b> {money(data.paymentTotals?.transfer)}</span></div>
    <section className="report-detail-grid"><article className="surface-card report-detail"><div className="detail-title"><div><span className="eyebrow">INGRESOS</span><h2>Detalle de ventas</h2></div><strong>{money(data.sales)}</strong></div>{data.salesDetail.length?<div className="detail-list">{data.salesDetail.map(sale=><article key={sale.id}><div className="detail-reference"><b>#{sale.number}</b><span><strong>{sale.reference}</strong><small>{labels[sale.serviceType]} · {formatDate(sale.date)}</small></span></div><div className="detail-values"><small>Alimentos {money(sale.foodSubtotal)}</small>{sale.serviceFee>0&&<small>{sale.serviceType==="delivery"?"Domicilio":"Empaque"} {money(sale.serviceFee)}</small>}<strong>{money(sale.total)}</strong></div></article>)}</div>:<EmptyState icon="IF" title="Sin ventas en este periodo" description="Los pedidos registrados aparecerán aquí."/>}</article>
      <article className="surface-card report-detail"><div className="detail-title"><div><span className="eyebrow">EGRESOS</span><h2>Detalle de salidas</h2></div><strong>{money(data.expenseTotal)}</strong></div>{data.expenseDetail.length?<div className="detail-list expense-list">{data.expenseDetail.map(expense=><article key={expense.id}><div className="detail-reference"><span className="expense-mark">−</span><span><strong>{expense.concept}</strong><small>{formatDate(expense.date)}</small></span></div><div className="detail-values"><strong>{money(expense.amount)}</strong></div></article>)}</div>:<EmptyState icon="−" title="Sin salidas en este periodo" description="Registra una salida desde Caja para verla aquí."/>}</article>
    </section>
    {(data.refundDetail||[]).length>0&&<section className="surface-card report-detail refund-detail"><div className="detail-title"><div><span className="eyebrow">DEVOLUCIONES</span><h2>Pedidos devueltos</h2></div><strong>{money(data.refundTotal)}</strong></div><div className="detail-list expense-list">{data.refundDetail.map(item=><article key={item.id}><div className="detail-reference"><span className="expense-mark">↩</span><span><strong>Pedido #{item.number}</strong><small>{item.reason} · {formatDate(item.date)}</small></span></div><div className="detail-values"><strong>{money(item.total)}</strong></div></article>)}</div></section>}
    <section className="surface-card report-note"><span>i</span><p><strong>Por ahora el informe muestra movimientos reales de ventas y caja.</strong> El costo de preparación de los platos y el cálculo de utilidad se agregarán en una etapa posterior.</p></section>
  </div>;
}
