import{useEffect,useState}from"react";
import PageHeader from"../../components/PageHeader";
import Modal from"../../components/Modal";
import EmptyState from"../../components/EmptyState";
import LoadingState from"../../components/LoadingState";
import{createTemplate,deleteTemplate,getCatalog,getTemplates,updateTemplate}from"../../controllers/operationsController";

const empty=()=>({id:null,name:"",basePrice:"",description:"",isActive:true,requirements:[]});
export default function TemplatesPage(){
 const[templates,setTemplates]=useState([]),[categories,setCategories]=useState([]),[draft,setDraft]=useState(null),[loading,setLoading]=useState(true),[error,setError]=useState(""),[message,setMessage]=useState("");
 const load=()=>{setLoading(true);Promise.all([getTemplates(),getCatalog()]).then(([items,catalog])=>{setTemplates(items);setCategories((catalog.categories||[]).filter(item=>item.is_active))}).catch(f=>setError(f.message)).finally(()=>setLoading(false))};useEffect(()=>{load()},[]);
 const edit=item=>setDraft({id:item.id,name:item.name,basePrice:Number(item.base_price),description:item.description||"",isActive:item.is_active,requirements:(item.template_requirements||[]).sort((a,b)=>a.sort_order-b.sort_order).map(requirement=>({categoryId:requirement.category_id,quantity:requirement.quantity}))});
 const addRequirement=()=>setDraft(current=>({...current,requirements:[...current.requirements,{categoryId:"",quantity:1}]}));
 const updateRequirement=(index,changes)=>setDraft(current=>({...current,requirements:current.requirements.map((item,i)=>i===index?{...item,...changes}:item)}));
 const save=async event=>{event.preventDefault();try{const payload={name:draft.name,basePrice:Number(draft.basePrice),description:draft.description,isActive:draft.isActive,requirements:draft.requirements};if(draft.id)await updateTemplate(draft.id,payload);else await createTemplate(payload);setDraft(null);setMessage("Plantilla guardada");await load()}catch(f){setError(f.message)}};
 const remove=async item=>{if(!window.confirm(`¿Retirar la plantilla “${item.name}”?`))return;try{await deleteTemplate(item.id);setMessage("Plantilla retirada");load()}catch(f){setError(f.message)}};
 if(loading)return <div className="content"><PageHeader eyebrow="PRECIOS" title="Plantillas"/><section className="surface-card"><LoadingState label="Cargando plantillas..."/></section></div>;
 return <div className="content"><PageHeader eyebrow="PRECIOS" title="Plantillas de precio" description="Define qué combinación de categorías recibe un precio especial." action={<button className="primary-action" onClick={()=>setDraft(empty())}>＋ Nueva plantilla</button>}/>{error&&<div className="form-alert module-alert">{error}</div>}{message&&<div className="success-alert module-alert">✓ {message}</div>}
  <section className="template-explanation surface-card"><span>¿Cómo funciona?</span><p>El empleado selecciona productos. Si la selección cumple una plantilla, el sistema aplica su precio automáticamente. Lo que sobre se cobra al precio individual.</p></section>
  <section className="template-grid">{templates.filter(item=>item.is_active).length?templates.filter(item=>item.is_active).map(item=><article className="surface-card" key={item.id}><div className="template-card-heading"><div><span className="eyebrow">PLANTILLA</span><h2>{item.name}</h2></div><strong>${Number(item.base_price).toLocaleString("es-CO")}</strong></div><p>{item.description||"Sin descripción"}</p><div className="requirement-list">{(item.template_requirements||[]).sort((a,b)=>a.sort_order-b.sort_order).map(requirement=><span key={requirement.id}><b>{requirement.quantity}</b> de {requirement.product_categories?.name}</span>)}</div><div className="template-actions"><button onClick={()=>edit(item)}>Editar</button><button className="danger-button" onClick={()=>remove(item)}>Retirar</button></div></article>):<EmptyState icon="PL" title="Aún no hay plantillas" description="Crea reglas como Bandeja, Almuerzo completo o Combo hamburguesa."/>}</section>
  {draft&&<Modal wide title={draft.id?"Editar plantilla":"Nueva plantilla de precio"} description="Selecciona las categorías y cuántos productos debe consumir la plantilla." onClose={()=>setDraft(null)}><form className="module-form template-form" onSubmit={save}><div className="form-columns"><label>Nombre<input value={draft.name} onChange={e=>setDraft({...draft,name:e.target.value})} placeholder="Ej. Almuerzo completo" required/></label><label>Precio de la plantilla<input type="number" min="0" value={draft.basePrice} onChange={e=>setDraft({...draft,basePrice:e.target.value})} required/></label></div><label>Descripción<textarea value={draft.description} onChange={e=>setDraft({...draft,description:e.target.value})} placeholder="Opcional"/></label><div className="template-requirements"><div><strong>Categorías requeridas</strong><button type="button" className="secondary-button" onClick={addRequirement}>＋ Categoría</button></div>{draft.requirements.map((requirement,index)=><div key={index}><select value={requirement.categoryId} onChange={e=>updateRequirement(index,{categoryId:e.target.value})} required><option value="">Seleccionar categoría...</option>{categories.filter(category=>!draft.requirements.some((item,i)=>i!==index&&item.categoryId===category.id)).map(category=><option key={category.id} value={category.id}>{category.name}</option>)}</select><label>Cantidad<input type="number" min="1" value={requirement.quantity} onChange={e=>updateRequirement(index,{quantity:Number(e.target.value)})}/></label><button type="button" onClick={()=>setDraft({...draft,requirements:draft.requirements.filter((_,i)=>i!==index)})}>×</button></div>)}</div><button className="primary-action" disabled={!draft.requirements.length}>Guardar plantilla</button></form></Modal>}
 </div>;
}
