import { useEffect, useState } from "react";
import PageHeader from "../../components/PageHeader";
import Modal from "../../components/Modal";
import LoadingState from "../../components/LoadingState";
import { createTable, getTables, updateTable } from "../../controllers/operationsController";

export default function TablesPage() {
  const [tables, setTables] = useState([]); const [open, setOpen] = useState(false); const [releaseTarget, setReleaseTarget] = useState(null); const [error, setError] = useState(""); const [loading, setLoading] = useState(true);
  const load = () => { setLoading(true); return getTables().then(setTables).catch((failure) => setError(failure.message)).finally(() => setLoading(false)); };
  useEffect(() => { load(); }, []);
  const add = async (event) => { event.preventDefault(); const form = new FormData(event.currentTarget); try { await createTable({ name: form.get("name"), seats: Number(form.get("seats")) }); setOpen(false); await load(); } catch (failure) { setError(failure.message); } };
  const toggle = async (table) => { if (table.status === "occupied") return setReleaseTarget(table); try { await updateTable(table.id, { status: "occupied" }); await load(); } catch (failure) { setError(failure.message); } };
  const confirmRelease = async () => { try { await updateTable(releaseTarget.id, { status: "free" }); setReleaseTarget(null); await load(); } catch (failure) { setError(failure.message); } };
  return <div className="content"><PageHeader eyebrow="SALÓN" title="Mesas" description="Consulta la ocupación y organiza el restaurante." action={<button className="primary-action" onClick={() => setOpen(true)}>＋ Nueva mesa</button>} />{error && <div className="form-alert module-alert">{error}</div>}{loading ? <section className="surface-card"><LoadingState label="Consultando estado de las mesas..." /></section> : <><div className="legend-row"><span><i className="dot free" />Libre</span><span><i className="dot busy" />Ocupada</span></div><section className="tables-board"><div className="zone-title"><div><span className="eyebrow">ZONA</span><h2>Salón principal</h2></div><strong>{tables.length} {tables.length === 1 ? "mesa" : "mesas"}</strong></div><div className="tables-grid">{tables.map((table) => <button className={`table-card ${table.status === "occupied" ? "ocupada" : "libre"}`} key={table.id} onClick={() => toggle(table)}><span>{table.name}</span><strong>{table.status === "occupied" ? "Ocupada" : "Libre"}</strong><small>{table.seats} personas</small><i /></button>)}<button className="add-table" onClick={() => setOpen(true)}>＋<span>Agregar mesa</span></button></div></section></>}{open && <Modal title="Nueva mesa" onClose={() => setOpen(false)}><form className="module-form" onSubmit={add}><label>Nombre<input name="name" required /></label><label>Capacidad<input name="seats" type="number" min="1" defaultValue="4" required /></label><button className="primary-action">Guardar mesa</button></form></Modal>}{releaseTarget && <Modal title={`Liberar ${releaseTarget.name}`} description="Hazlo solo si el cliente ya terminó y no existe un pedido pendiente en esta mesa." onClose={() => setReleaseTarget(null)}><div className="cancel-confirmation"><strong>¿Confirmas que la mesa está libre?</strong><p>El cambio es manual y no modifica ni cobra pedidos asociados.</p></div><div className="modal-actions"><button className="secondary-button" onClick={() => setReleaseTarget(null)}>Mantener ocupada</button><button className="danger-button" onClick={confirmRelease}>Sí, liberar mesa</button></div></Modal>}</div>;
}
