import { useEffect, useState } from "react";
import PageHeader from "../../components/PageHeader";
import { getRestaurantProfile, updateRestaurantProfile } from "../../controllers/authController";

export default function SettingsPage(){
  const[profile,setProfile]=useState(null);const[saved,setSaved]=useState(false);const[error,setError]=useState("");
  useEffect(()=>{getRestaurantProfile().then(setProfile).catch(failure=>setError(failure.message))},[]);
  const change=(group,key,value)=>setProfile(current=>({...current,[group]:{...current[group],[key]:value}}));
  const submit=async(event)=>{event.preventDefault();setSaved(false);setError("");try{const data=await updateRestaurantProfile({tenant:{business_name:profile.tenant.business_name,legal_name:profile.tenant.legal_name,document_type:profile.tenant.document_type,document_number:profile.tenant.document_number,verification_digit:profile.tenant.verification_digit,billing_email:profile.tenant.billing_email,phone:profile.tenant.phone},restaurant:{name:profile.restaurant.name},branch:{name:profile.branch.name,address:profile.branch.address,city:profile.branch.city}});setProfile(data);setSaved(true)}catch(failure){setError(failure.message)}};
  return <div className="content"><PageHeader eyebrow="ADMINISTRACIÓN" title="Configuración" description="Mantén completos los datos que aparecen en comprobantes y documentos."/>{error&&<div className="form-alert module-alert">{error}</div>}<div className="settings-layout"><aside className="settings-nav"><button className="active">Datos del restaurante</button><button>Sedes y horarios</button><button>Impuestos y moneda</button><button>Plan y facturación</button><button>Seguridad</button></aside><section className="surface-card settings-panel"><div><h2>Identificación y contacto</h2><p>Los cambios se usarán en los próximos comprobantes impresos.</p></div>{profile?<form className="module-form" onSubmit={submit}><div className="form-columns"><label>Razón social<input value={profile.tenant.legal_name||""} onChange={event=>change("tenant","legal_name",event.target.value)} required/></label><label>Nombre comercial<input value={profile.restaurant.name||""} onChange={event=>change("restaurant","name",event.target.value)} required/></label></div><div className="document-columns"><label>Tipo<select value={profile.tenant.document_type||"NIT"} onChange={event=>change("tenant","document_type",event.target.value)}><option>NIT</option><option>CC</option><option>CE</option><option>PASAPORTE</option></select></label><label>Número<input value={profile.tenant.document_number||""} onChange={event=>change("tenant","document_number",event.target.value)}/></label><label>DV<input maxLength="1" value={profile.tenant.verification_digit||""} onChange={event=>change("tenant","verification_digit",event.target.value)}/></label></div><div className="form-columns"><label>Teléfono<input value={profile.tenant.phone||""} onChange={event=>change("tenant","phone",event.target.value)}/></label><label>Correo del negocio<input type="email" value={profile.tenant.billing_email||""} onChange={event=>change("tenant","billing_email",event.target.value)}/></label></div><label>Dirección<input value={profile.branch.address||""} onChange={event=>change("branch","address",event.target.value)}/></label><div className="form-columns"><label>Ciudad<input value={profile.branch.city||""} onChange={event=>change("branch","city",event.target.value)}/></label><label>Nombre de la sede<input value={profile.branch.name||""} onChange={event=>change("branch","name",event.target.value)}/></label></div><div className="form-footer">{saved&&<span className="save-confirmation">✓ Cambios guardados</span>}<button className="primary-action">Guardar cambios</button></div></form>:<div className="settings-loading">Cargando datos...</div>}</section></div></div>;
}
