import {useEffect,useMemo,useState} from "react";
import PageHeader from "../../components/PageHeader";
import EmptyState from "../../components/EmptyState";
import Modal from "../../components/Modal";
import LoadingState from "../../components/LoadingState";
import {createCategory,createProduct,deleteProduct,getCatalog,getDailyMenu,saveDailyMenu,saveProductOptions,updateDailyMenuAvailability,updateProduct} from "../../controllers/operationsController";

const localDate=()=>new Intl.DateTimeFormat("en-CA",{timeZone:"America/Bogota",year:"numeric",month:"2-digit",day:"2-digit"}).format(new Date());
const emptyProduct=()=>({id:null,name:"",categoryId:"",price:"",description:"",productType:"simple",isActive:true,groups:[]});
const emptyGroup=()=>({name:"",minimumSelections:1,maximumSelections:1,options:[{productId:"",priceDelta:0,stockQuantity:""}]});

export default function MenuPage(){
 const[tab,setTab]=useState("daily"),[productOpen,setProductOpen]=useState(false),[categoryOpen,setCategoryOpen]=useState(false),[products,setProducts]=useState([]),[categories,setCategories]=useState([]),[date,setDate]=useState(localDate()),[dailyMenu,setDailyMenu]=useState(null),[selectedIds,setSelectedIds]=useState([]),[stockQuantities,setStockQuantities]=useState({}),[componentStocks,setComponentStocks]=useState({}),[error,setError]=useState(""),[message,setMessage]=useState(""),[loading,setLoading]=useState(true),[search,setSearch]=useState(""),[draft,setDraft]=useState(emptyProduct());
 const loadCatalog=()=>getCatalog().then(data=>{setProducts(data.products);setCategories(data.categories)});
 const loadDaily=(selectedDate=date)=>getDailyMenu(selectedDate).then(data=>{setDailyMenu(data.menu);setSelectedIds(data.menu?.daily_menu_items?.map(item=>item.product_id)||[]);setStockQuantities(Object.fromEntries((data.menu?.daily_menu_items||[]).map(item=>[item.product_id,item.stock_quantity??""])));setComponentStocks(Object.fromEntries((data.menu?.daily_menu_option_stocks||[]).map(item=>[item.option_id,item.stock_quantity??""])))});
 const load=()=>{setLoading(true);return Promise.all([loadCatalog(),loadDaily()]).catch(f=>setError(f.message)).finally(()=>setLoading(false))};useEffect(()=>{load()},[]);
 const changeDate=async value=>{setDate(value);setMessage("");try{await loadDaily(value)}catch(f){setError(f.message)}};
 const toggleSelection=id=>setSelectedIds(current=>current.includes(id)?current.filter(item=>item!==id):[...current,id]);
 const publish=async()=>{try{setError("");const result=await saveDailyMenu(date,selectedIds.map(productId=>{const product=products.find(item=>item.id===productId);return{productId,quantity:stockQuantities[productId]===""||stockQuantities[productId]===undefined?null:Number(stockQuantities[productId]),optionStocks:(product?.product_option_groups||[]).flatMap(group=>group.product_options||[]).map(option=>({optionId:option.id,quantity:componentStocks[option.id]===""||componentStocks[option.id]===undefined?null:Number(componentStocks[option.id])}))}}));setDailyMenu(result.menu);setComponentStocks(Object.fromEntries((result.menu?.daily_menu_option_stocks||[]).map(item=>[item.option_id,item.stock_quantity??""])));setMessage("Menú del día publicado correctamente")}catch(f){setError(f.message)}};
 const toggleAvailability=async item=>{try{await updateDailyMenuAvailability(item.id,item.availability==="available"?"sold_out":"available");await loadDaily(date)}catch(f){setError(f.message)}};
 const openCreate=(type="simple")=>{setDraft({...emptyProduct(),productType:type,groups:type==="composite"?[emptyGroup()]:[]});setProductOpen(true)};
 const openEdit=product=>{setDraft({id:product.id,name:product.name,categoryId:product.category_id||"",price:Number(product.price),description:product.description||"",productType:product.product_type||"simple",isActive:product.is_active,groups:(product.product_option_groups||[]).sort((a,b)=>a.sort_order-b.sort_order).map(group=>({name:group.name,minimumSelections:group.minimum_selections,maximumSelections:group.maximum_selections,options:(group.product_options||[]).sort((a,b)=>a.sort_order-b.sort_order).map(option=>({productId:option.component_product_id,priceDelta:Number(option.price_delta),stockQuantity:option.stock_quantity??""}))}))});setProductOpen(true)};
 const updateGroup=(index,changes)=>setDraft(current=>({...current,groups:current.groups.map((group,i)=>i===index?{...group,...changes}:group)}));
 const updateOption=(groupIndex,optionIndex,changes)=>setDraft(current=>({...current,groups:current.groups.map((group,i)=>i===groupIndex?{...group,options:group.options.map((option,j)=>j===optionIndex?{...option,...changes}:option)}:group)}));
 const saveProduct=async event=>{event.preventDefault();try{setError("");const values={name:draft.name,categoryId:draft.categoryId||null,price:Number(draft.price),description:draft.description,productType:draft.productType,isActive:draft.isActive};const product=draft.id?await updateProduct(draft.id,values):await createProduct(values);if(draft.productType==="composite")await saveProductOptions(product.id,draft.groups);else if(draft.id)await saveProductOptions(product.id,[]);setProductOpen(false);setMessage(draft.id?"Producto actualizado":"Producto creado");await loadCatalog()}catch(f){setError(f.message)}};
 const remove=async product=>{if(!window.confirm(`¿Retirar “${product.name}” del menú? Los pedidos anteriores conservarán su información.`))return;try{await deleteProduct(product.id);setMessage("Producto retirado del menú");await Promise.all([loadCatalog(),loadDaily(date)])}catch(f){setError(f.message)}};
 const addCategory=async event=>{event.preventDefault();try{await createCategory(new FormData(event.currentTarget).get("name"));setCategoryOpen(false);await loadCatalog()}catch(f){setError(f.message)}};
 const itemByProduct=new Map((dailyMenu?.daily_menu_items||[]).map(item=>[item.product_id,item]));
 const visibleProducts=useMemo(()=>products.filter(product=>product.name.toLowerCase().includes(search.toLowerCase())),[products,search]);
 if(loading)return <div className="content"><PageHeader eyebrow="CATÁLOGO" title="Menú"/><section className="surface-card"><LoadingState label="Cargando catálogo y menú del día..."/></section></div>;
 return <div className="content"><PageHeader eyebrow="CATÁLOGO" title="Menú" description="Crea comidas individuales y combínalas en bandejas o promociones." secondary={<button className="secondary-button" onClick={()=>setCategoryOpen(true)}>＋ Categoría</button>} action={<div className="module-actions"><button className="secondary-button" onClick={()=>openCreate("simple")}>＋ Nueva comida</button><button className="primary-action" onClick={()=>openCreate("composite")}>＋ Crear combo compuesto</button></div>}/>{error&&<div className="form-alert module-alert">{error}</div>}{message&&<div className="success-alert module-alert">✓ {message}</div>}
  <div className="menu-tabs"><button className={tab==="daily"?"active":""} onClick={()=>setTab("daily")}>Menú del día</button><button className={tab==="catalog"?"active":""} onClick={()=>setTab("catalog")}>Todos los productos</button></div>
  {tab==="daily"?<section className="daily-menu-layout"><article className="surface-card daily-selector"><div className="daily-menu-heading"><div><span className="eyebrow">PROGRAMACIÓN</span><h2>Selecciona los productos disponibles</h2><p>Estos serán visibles al crear pedidos y en las aplicaciones móviles.</p></div><label>Fecha<input type="date" value={date} onChange={e=>changeDate(e.target.value)}/></label></div>
   {!products.some(p=>p.is_active)?<EmptyState icon="MN" title="Primero crea productos" description="El catálogo maestro está vacío."/>:<div className="daily-product-list">{[...categories,{id:null,name:"Otros"}].map(category=>{const entries=products.filter(product=>product.category_id===category.id&&product.is_active);if(!entries.length)return null;return <section key={category.id||"other"}><h3>{category.name}</h3>{entries.map(product=>{const checked=selectedIds.includes(product.id),dailyItem=itemByProduct.get(product.id),options=(product.product_option_groups||[]).flatMap(group=>(group.product_options||[]).map(option=>({...option,groupName:group.name})));return <article key={product.id} className={`${checked?"selected":""} ${checked&&options.length?"daily-composite-row":""}`}><button className="daily-check" onClick={()=>toggleSelection(product.id)}>{checked?"✓":""}</button><div><strong>{product.name}{product.product_type==="composite"?" · Compuesto":""}</strong><small>${Number(product.price).toLocaleString("es-CO")}</small>{checked&&options.length>0&&<div className="daily-component-stocks"><b>Existencias de las opciones para este día</b>{options.map(option=><label key={option.id}><span>{option.groupName}: {option.name}{Number(option.price_delta)>0?` (+$${Number(option.price_delta).toLocaleString("es-CO")})`:""}</span><input type="number" min="0" value={componentStocks[option.id]??""} onChange={e=>setComponentStocks(current=>({...current,[option.id]:e.target.value}))} placeholder="Sin límite"/></label>)}</div>}</div>{checked&&<label className="stock-input"><span>Combos totales</span><input type="number" min="0" value={stockQuantities[product.id]??""} onChange={e=>setStockQuantities(current=>({...current,[product.id]:e.target.value}))} placeholder="Sin límite"/></label>}{dailyItem&&<button className={`availability-button ${dailyItem.availability}`} onClick={()=>toggleAvailability(dailyItem)}>{dailyItem.availability==="available"?(dailyItem.remaining_quantity===null?"Disponible":`${dailyItem.remaining_quantity} restantes`):"Agotado"}</button>}</article>})}</section>})}</div>}<div className="daily-footer"><span><strong>{selectedIds.length}</strong> productos seleccionados</span><button className="primary-action" onClick={publish}>Publicar menú del día</button></div></article><aside className="surface-card daily-help"><span>MENÚ</span><h2>{date===localDate()?"Menú de hoy":"Menú programado"}</h2><strong>{selectedIds.length} platos</strong><p>Las existencias de cada proteína o componente se configuran por fecha y se descuentan al vender.</p></aside></section>
  :<><div className="module-toolbar"><div className="segmented"><button className="active">Todos <b>{products.length}</b></button></div><input className="search-input" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Buscar producto..."/></div><section className="surface-card">{!visibleProducts.length?<EmptyState icon="MN" title="No hay productos" description="Crea tu primer plato o cambia la búsqueda."/>:<div className="product-grid">{visibleProducts.map(product=><article key={product.id} className={!product.is_active?"product-inactive":""}><span className="product-photo">{product.name.slice(0,2).toUpperCase()}</span><div><small>{product.product_categories?.name||"Sin categoría"} · {product.product_type==="composite"?"Plato compuesto":"Producto simple"}</small><h3>{product.name}</h3><strong>${Number(product.price).toLocaleString("es-CO")}</strong></div><div className="catalog-actions"><span className={`status-pill ${product.is_active?"ready":"cancelled"}`}>{product.is_active?"Activo":"Retirado"}</span><button onClick={()=>openEdit(product)}>Editar</button>{product.is_active&&<button className="remove-product" onClick={()=>remove(product)}>Retirar</button>}</div></article>)}</div>}</section></>}
  {categoryOpen&&<Modal title="Nueva categoría" onClose={()=>setCategoryOpen(false)}><form className="module-form" onSubmit={addCategory}><label>Nombre<input name="name" required/></label><button className="primary-action">Guardar categoría</button></form></Modal>}
  {productOpen&&<Modal wide title={draft.id?"Editar producto":draft.productType==="composite"?"Crear combo compuesto":"Crear comida"} description={draft.productType==="composite"?"Selecciona comidas existentes para construir el combo.":"Esta comida podrá venderse sola o formar parte de un combo."} onClose={()=>setProductOpen(false)}><form className="module-form composite-form" onSubmit={saveProduct}><label>Nombre<input value={draft.name} onChange={e=>setDraft({...draft,name:e.target.value})} required/></label><div className="form-columns"><label>Categoría<select value={draft.categoryId} onChange={e=>setDraft({...draft,categoryId:e.target.value})}><option value="">Sin categoría</option>{categories.map(category=><option key={category.id} value={category.id}>{category.name}</option>)}</select></label><label>{draft.productType==="composite"?"Precio base del combo":"Precio"}<input type="number" min="0" value={draft.price} onChange={e=>setDraft({...draft,price:e.target.value})} required/></label></div><label>Descripción<textarea value={draft.description} onChange={e=>setDraft({...draft,description:e.target.value})}/></label>
   {draft.productType==="composite"&&<div className="composition-builder"><div className="builder-heading"><div><strong>Comidas incluidas</strong><small>Crea grupos como Principio, Sopa y Proteína; las existencias se indican al publicar el menú del día.</small></div><button type="button" className="secondary-button" onClick={()=>setDraft({...draft,groups:[...draft.groups,emptyGroup()]})}>＋ Grupo</button></div>{draft.groups.map((group,groupIndex)=><section key={groupIndex}><div className="group-heading"><input placeholder="Nombre: Proteína" value={group.name} onChange={e=>updateGroup(groupIndex,{name:e.target.value})} required/><label>Mín.<input type="number" min="0" value={group.minimumSelections} onChange={e=>updateGroup(groupIndex,{minimumSelections:Number(e.target.value)})}/></label><label>Máx.<input type="number" min="1" value={group.maximumSelections} onChange={e=>updateGroup(groupIndex,{maximumSelections:Number(e.target.value)})}/></label><button type="button" onClick={()=>setDraft({...draft,groups:draft.groups.filter((_,i)=>i!==groupIndex)})}>×</button></div><div className="option-list">{group.options.map((option,optionIndex)=><div key={optionIndex}><select value={option.productId} onChange={e=>updateOption(groupIndex,optionIndex,{productId:e.target.value})} required><option value="">Seleccionar comida...</option>{products.filter(item=>item.product_type!=="composite"&&item.is_active&&item.id!==draft.id).map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select><label>Adicional sobre el combo<input type="number" min="0" step="100" value={option.priceDelta} onChange={e=>updateOption(groupIndex,optionIndex,{priceDelta:e.target.value})}/></label><button type="button" onClick={()=>updateGroup(groupIndex,{options:group.options.filter((_,i)=>i!==optionIndex)})}>×</button></div>)}</div><button type="button" className="add-option" onClick={()=>updateGroup(groupIndex,{options:[...group.options,{productId:"",priceDelta:0,stockQuantity:""}]})}>＋ Agregar comida</button></section>)}</div>}
   {draft.id&&<label className="check-label"><input type="checkbox" checked={draft.isActive} onChange={e=>setDraft({...draft,isActive:e.target.checked})}/>Disponible en el catálogo</label>}<button className="primary-action">Guardar producto</button></form></Modal>}
 </div>;
}
