import{useEffect,useMemo,useState}from"react";
import PageHeader from"../../components/PageHeader";
import EmptyState from"../../components/EmptyState";
import LoadingState from"../../components/LoadingState";
import Modal from"../../components/Modal";
import{cancelOrder,createOrder,editOrder,getDailyMenu,getOrders,getTables,getTemplates,payOrder,refundOrder}from"../../controllers/operationsController";

const serviceOptions=[{id:"table",title:"Para mesa",description:"Consumo en el restaurante",icon:"MS"},{id:"takeaway",title:"Para llevar",description:"El cliente recoge el pedido",icon:"LL"},{id:"delivery",title:"Domicilio",description:"El pedido será enviado",icon:"DM"}];
const today=()=>new Intl.DateTimeFormat("en-CA",{timeZone:"America/Bogota",year:"numeric",month:"2-digit",day:"2-digit"}).format(new Date());
const labels={table:"Para mesa",takeaway:"Para llevar",delivery:"Domicilio"};
const statusLabels={new:"Nuevo",preparing:"Preparando",ready:"Listo",delivered:"Entregado",paid:"Pagado",cancelled:"Cancelado",refunded:"Devuelto"};
const plural=(value,singular,pluralWord)=>`${value} ${value===1?singular:pluralWord}`;
const newPreparation=()=>({id:crypto.randomUUID(),ingredientIds:[]});

const recognizePreparation=(preparation,products,templates)=>{
 const ingredients=preparation.ingredientIds.map(id=>products.find(product=>product.id===id)).filter(Boolean);
 const matches=templates.filter(template=>template.is_active&&(template.template_requirements||[]).every(requirement=>ingredients.filter(product=>product.category_id===requirement.category_id).length>=Number(requirement.quantity))).sort((a,b)=>b.template_requirements.reduce((sum,item)=>sum+Number(item.quantity),0)-a.template_requirements.reduce((sum,item)=>sum+Number(item.quantity),0));
 const template=matches[0]||null,included=new Set();if(template)for(const requirement of [...template.template_requirements].sort((a,b)=>a.sort_order-b.sort_order)){let remaining=Number(requirement.quantity);ingredients.forEach((product,index)=>{if(remaining>0&&!included.has(index)&&product.category_id===requirement.category_id){included.add(index);remaining--}})}
 let total=template?Number(template.base_price):0;ingredients.forEach((product,index)=>{total+=template&&included.has(index)?Number(product.template_surcharge||0):Number(product.price)});
 return{template,ingredients,included,total};
};

export default function OrdersPage(){
 const[open,setOpen]=useState(false),[step,setStep]=useState(1),[orders,setOrders]=useState([]),[products,setProducts]=useState([]),[templates,setTemplates]=useState([]),[tables,setTables]=useState([]),[editingOrder,setEditingOrder]=useState(null),[filter,setFilter]=useState("all");
 const[serviceType,setServiceType]=useState("table"),[tableId,setTableId]=useState(""),[customerName,setCustomerName]=useState(""),[notes,setNotes]=useState(""),[serviceFee,setServiceFee]=useState(0);
 const[preparations,setPreparations]=useState([]),[activePreparationId,setActivePreparationId]=useState(null),[individuals,setIndividuals]=useState({}),[previousUsage,setPreviousUsage]=useState({}),[activeCategory,setActiveCategory]=useState("all"),[search,setSearch]=useState("");
 const[error,setError]=useState(""),[saving,setSaving]=useState(false),[loading,setLoading]=useState(true),[paymentOrder,setPaymentOrder]=useState(null),[paymentMode,setPaymentMode]=useState("cash"),[paymentParts,setPaymentParts]=useState({cash:"",card:"",transfer:""}),[cancelTarget,setCancelTarget]=useState(null),[refundTarget,setRefundTarget]=useState(null),[refundReason,setRefundReason]=useState("");

 const load=async(silent=false)=>{if(!silent)setLoading(true);try{const[orderData,dailyData,tableData,templateData]=await Promise.all([getOrders(),getDailyMenu(today()),getTables(),getTemplates()]);setOrders(orderData);setProducts((dailyData.menu?.daily_menu_items||[]).filter(item=>item.products?.is_active&&item.products?.product_type!=="composite").map(item=>({...item.products,price:item.price_override??item.products.price,dailyMenuItemId:item.id,remainingQuantity:item.remaining_quantity,availability:item.availability})));setTables(tableData);setTemplates(templateData||[]);window.dispatchEvent(new CustomEvent("orders:count",{detail:orderData.filter(order=>!["paid","cancelled","refunded"].includes(order.status)).length}))}catch(f){setError(f.message)}finally{if(!silent)setLoading(false)}};
 useEffect(()=>{load()},[]);
 useEffect(()=>{const timer=window.setInterval(()=>{if(!open&&!paymentOrder&&!cancelTarget&&!refundTarget)load(true)},8000);return()=>window.clearInterval(timer)},[open,paymentOrder,cancelTarget,refundTarget]);

 const categories=useMemo(()=>{const map=new Map();products.forEach(product=>{const id=product.category_id||"other",name=product.product_categories?.name||"Otros";if(!map.has(id))map.set(id,{id,name,count:0});map.get(id).count++});return[...map.values()]},[products]);
 const visibleProducts=products.filter(product=>(activeCategory==="all"||product.category_id===activeCategory||(activeCategory==="other"&&!product.category_id))&&product.name.toLowerCase().includes(search.toLowerCase()));
 const recognized=useMemo(()=>preparations.map(preparation=>({...preparation,...recognizePreparation(preparation,products,templates)})),[preparations,products,templates]);
 const foodTotal=recognized.reduce((sum,item)=>sum+item.total,0)+Object.entries(individuals).reduce((sum,[id,quantity])=>sum+Number(products.find(product=>product.id===id)?.price||0)*Number(quantity),0);
 const total=foodTotal+(serviceType==="table"?0:Number(serviceFee||0));
 const usage=useMemo(()=>{const result={...individuals};preparations.flatMap(item=>item.ingredientIds).forEach(id=>{result[id]=Number(result[id]||0)+1});return result},[preparations,individuals]);
 const capacity=id=>{const product=products.find(item=>item.id===id);return product?.remainingQuantity===null?null:Number(product?.remainingQuantity||0)+Number(previousUsage[id]||0)};
 const canAdd=id=>capacity(id)===null||Number(usage[id]||0)<capacity(id);
 const activePreparation=preparations.find(item=>item.id===activePreparationId);
 const freeTables=tables.filter(table=>table.status==="free"||table.id===editingOrder?.table_id);
 const visibleOrders=orders.filter(order=>filter==="all"||order.status===filter);

 const resetForm=()=>{setStep(1);setEditingOrder(null);setServiceType("table");setTableId("");setCustomerName("");setNotes("");setServiceFee(0);setPreparations([]);setActivePreparationId(null);setIndividuals({});setPreviousUsage({});setActiveCategory("all");setSearch("");setError("")};
 const beginOrder=()=>{resetForm();setOpen(true)};
 const beginEdit=order=>{const prepItems=(order.order_items||[]).filter(item=>item.line_type==="preparation"),normalItems=(order.order_items||[]).filter(item=>item.line_type!=="preparation"),nextPreparations=prepItems.map(item=>({id:item.id,ingredientIds:(item.selections||[]).map(selection=>selection.productId)})),nextIndividuals=Object.fromEntries(normalItems.filter(item=>item.product_id).map(item=>[item.product_id,Number(item.quantity)])),oldUsage={...nextIndividuals};nextPreparations.flatMap(item=>item.ingredientIds).forEach(id=>oldUsage[id]=Number(oldUsage[id]||0)+1);setEditingOrder(order);setServiceType(order.service_type);setTableId(order.table_id||"");setCustomerName(order.customer_name||"");setNotes(order.notes||"");setServiceFee(Number(order.service_fee||0));setPreparations(nextPreparations);setActivePreparationId(nextPreparations[0]?.id||null);setIndividuals(nextIndividuals);setPreviousUsage(oldUsage);setStep(1);setError("");setOpen(true)};
 const continueToMenu=()=>{if(serviceType==="table"&&!tableId)return setError("Selecciona una mesa disponible");setError("");setStep(2);if(!preparations.length){const preparation=newPreparation();setPreparations([preparation]);setActivePreparationId(preparation.id)}};
 const addPreparation=()=>{const preparation=newPreparation();setPreparations(current=>[...current,preparation]);setActivePreparationId(preparation.id)};
 const duplicatePreparation=id=>{const source=preparations.find(item=>item.id===id);if(!source)return;const copy={id:crypto.randomUUID(),ingredientIds:[...source.ingredientIds]};if(copy.ingredientIds.some(productId=>!canAdd(productId)))return setError("No hay existencias suficientes para duplicar esta preparación");setPreparations(current=>[...current,copy]);setActivePreparationId(copy.id)};
 const removePreparation=id=>{setPreparations(current=>current.filter(item=>item.id!==id));if(activePreparationId===id)setActivePreparationId(preparations.find(item=>item.id!==id)?.id||null)};
 const toggleIngredient=id=>{if(!activePreparation)return setError("Primero crea o selecciona una preparación");const selected=activePreparation.ingredientIds.includes(id);if(!selected&&!canAdd(id))return setError("No quedan unidades disponibles");setPreparations(current=>current.map(item=>item.id===activePreparation.id?{...item,ingredientIds:selected?item.ingredientIds.filter(productId=>productId!==id):[...item.ingredientIds,id]}:item));setError("")};
 const changeIndividual=(id,change)=>{const next=Math.max(0,Number(individuals[id]||0)+change);const usedInPreparations=preparations.flatMap(item=>item.ingredientIds).filter(productId=>productId===id).length,limit=capacity(id);if(limit!==null&&usedInPreparations+next>limit)return setError("No quedan unidades disponibles");setIndividuals(current=>({...current,[id]:next}));setError("")};
 const saveOrder=async()=>{const nonempty=preparations.filter(item=>item.ingredientIds.length);const itemPayload=Object.entries(individuals).filter(([,quantity])=>Number(quantity)>0).map(([productId,quantity])=>({productId,quantity:Number(quantity)}));if(!nonempty.length&&!itemPayload.length)return setError("Agrega al menos un producto");setSaving(true);setError("");const payload={serviceType,tableId:serviceType==="table"?tableId:null,customerName:customerName||null,notes:notes||null,serviceFee:serviceType==="table"?0:Number(serviceFee||0),preparations:nonempty.map(item=>({ingredientIds:item.ingredientIds})),items:itemPayload};try{if(editingOrder)await editOrder(editingOrder.id,payload);else await createOrder(payload);setOpen(false);resetForm();await load()}catch(f){setError(f.message)}finally{setSaving(false)}};
 const beginPayment=order=>{setPaymentOrder(order);setPaymentMode("cash");setPaymentParts({cash:"",card:"",transfer:""});setError("")};
 const confirmPayment=async()=>{const payments=paymentMode==="mixed"?Object.entries(paymentParts).filter(([,amount])=>Number(amount)>0).map(([method,amount])=>({method,amount:Number(amount)})):[{method:paymentMode,amount:Number(paymentOrder.total)}];setSaving(true);try{await payOrder(paymentOrder.id,payments);setPaymentOrder(null);await load()}catch(f){setError(f.message)}finally{setSaving(false)}};
 const confirmCancellation=async()=>{setSaving(true);try{await cancelOrder(cancelTarget.id);setCancelTarget(null);await load()}catch(f){setError(f.message)}finally{setSaving(false)}};
 const confirmRefund=async()=>{if(refundReason.trim().length<3)return setError("Escribe el motivo de la devolución");setSaving(true);try{await refundOrder(refundTarget.id,refundReason);setRefundTarget(null);setRefundReason("");await load()}catch(f){setError(f.message)}finally{setSaving(false)}};

 if(loading)return <div className="content"><PageHeader eyebrow="OPERACIÓN" title="Pedidos"/><section className="surface-card"><LoadingState label="Consultando pedidos..."/></section></div>;
 return <div className="content"><PageHeader eyebrow="OPERACIÓN" title="Pedidos" description="Crea preparaciones por comensal y deja que el sistema reconozca su precio." action={<button className="primary-action" onClick={beginOrder}>＋ Nuevo pedido</button>}/>{error&&!open&&!paymentOrder&&!cancelTarget&&!refundTarget&&<div className="form-alert module-alert">{error}</div>}
  <div className="module-toolbar"><div className="segmented"><button className={filter==="all"?"active":""} onClick={()=>setFilter("all")}>Todos <b>{orders.length}</b></button><button className={filter==="preparing"?"active":""} onClick={()=>setFilter("preparing")}>Preparando <b>{orders.filter(order=>order.status==="preparing").length}</b></button><button className={filter==="ready"?"active":""} onClick={()=>setFilter("ready")}>Listos <b>{orders.filter(order=>order.status==="ready").length}</b></button></div></div>
  <section className="surface-card">{visibleOrders.length?<div className="data-list">{visibleOrders.map(order=>{const preparationCount=(order.order_items||[]).filter(item=>item.line_type==="preparation").reduce((sum,item)=>sum+Number(item.quantity),0),additionalCount=(order.order_items||[]).filter(item=>item.line_type!=="preparation").reduce((sum,item)=>sum+Number(item.quantity),0),contentsLabel=[preparationCount?plural(preparationCount,"preparación","preparaciones"):null,additionalCount?plural(additionalCount,"adicional","adicionales"):null].filter(Boolean).join(" · ")||"Sin productos",pending=!["paid","cancelled","refunded"].includes(order.status);return <article key={order.id}><span className="list-avatar amber">#{order.order_number}</span><div><strong>{order.dining_tables?.name||order.customer_name||"Cliente"}</strong><small>{labels[order.service_type]} · {contentsLabel}</small></div><span className={`status-pill ${order.status}`}>{statusLabels[order.status]||order.status}</span><strong>${Number(order.total).toLocaleString("es-CO")}</strong><div className="order-row-actions">{pending&&<button onClick={()=>beginEdit(order)}>Editar</button>}{pending&&<button className="pay-action" onClick={()=>beginPayment(order)}>Cobrar</button>}{order.status!=="cancelled"&&<button onClick={()=>window.open(`/imprimir/pedido/${order.id}?tipo=cuenta`,"_blank")}>Cuenta</button>}{["new","preparing","ready"].includes(order.status)&&<button onClick={()=>window.open(`/imprimir/pedido/${order.id}?tipo=comanda`,"_blank")}>Comanda</button>}{pending&&<button className="cancel-action" onClick={()=>setCancelTarget(order)}>Cancelar</button>}{order.status==="paid"&&<button className="refund-action" onClick={()=>{setRefundTarget(order);setRefundReason("")}}>Devolver</button>}</div></article>})}</div>:<EmptyState icon="PD" title="No hay pedidos" description="Los pedidos aparecerán aquí."/>}</section>

  {open&&<Modal wide title={step===1?(editingOrder?`Editar pedido #${editingOrder.order_number}`:"¿Cómo se entregará el pedido?"):"Armar pedido"} description={step===1?"Selecciona el servicio.":"Cada preparación representa una persona o plato diferente."} onClose={()=>{setOpen(false);resetForm()}}><div className="order-steps"><span className="active">1 <b>Servicio</b></span><i/><span className={step===2?"active":""}>2 <b>Preparaciones</b></span></div>{step===1?<div><div className="service-options">{serviceOptions.map(option=><button key={option.id} className={serviceType===option.id?"active":""} onClick={()=>setServiceType(option.id)}><span>{option.icon}</span><strong>{option.title}</strong><small>{option.description}</small></button>)}</div>{serviceType==="table"&&<div className="table-picker"><span className="form-section-title">MESA</span><div>{freeTables.map(table=><button key={table.id} className={tableId===table.id?"active":""} onClick={()=>setTableId(table.id)}><strong>{table.name}</strong><small>{table.seats} personas</small></button>)}</div></div>}{serviceType!=="table"&&<div className="service-extra-fields customer-service-fields"><label className="standalone-field">Nombre del cliente<input type="text" value={customerName} onChange={e=>setCustomerName(e.target.value)} placeholder="Ej. Carlos Pérez"/></label><label className="standalone-field">{serviceType==="delivery"?"Dirección u observación":"Observación del pedido"}<textarea value={notes} onChange={e=>setNotes(e.target.value)} placeholder={serviceType==="delivery"?"Dirección, barrio o indicaciones":"Detalles opcionales"}/></label><label className="standalone-field">{serviceType==="delivery"?"Costo de domicilio":"Costo de empaque"}<input type="number" min="0" value={serviceFee} onChange={e=>setServiceFee(e.target.value)}/></label></div>}{serviceType==="table"&&<label className="standalone-field">Observaciones<textarea value={notes} onChange={e=>setNotes(e.target.value)}/></label>}{error&&<div className="form-alert">{error}</div>}<button className="primary-action order-next" onClick={continueToMenu}>Continuar</button></div>
  :<div className="pos-builder"><div className="pos-catalog"><div className="category-tile-bar"><button className={activeCategory==="all"?"active":""} onClick={()=>setActiveCategory("all")}>Todos</button>{categories.map(category=><button key={category.id} className={activeCategory===category.id?"active":""} onClick={()=>setActiveCategory(category.id)}>{category.name}<small>{category.count}</small></button>)}</div><input className="pos-search" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Buscar producto..."/><div className="ingredient-grid">{visibleProducts.map(product=>{const selected=activePreparation?.ingredientIds.includes(product.id),available=canAdd(product.id);return <article key={product.id} className={selected?"selected":""}><button className="ingredient-main" disabled={!selected&&!available} onClick={()=>toggleIngredient(product.id)}><span>{product.name.slice(0,2).toUpperCase()}</span><strong>{product.name}</strong><small>{product.product_categories?.name||"Otros"} · ${Number(product.price).toLocaleString("es-CO")}</small>{product.remainingQuantity!==null&&<em>{product.remainingQuantity} disponibles</em>}</button><div><button onClick={()=>changeIndividual(product.id,-1)}>−</button><b>{individuals[product.id]||0} extra</b><button onClick={()=>changeIndividual(product.id,1)} disabled={!available}>＋</button></div></article>})}</div></div>
   <aside className="preparation-cart"><div className="cart-heading"><div><strong>{serviceType==="table"?tables.find(table=>table.id===tableId)?.name:labels[serviceType]}</strong><small>Pedido actual</small></div><button onClick={addPreparation}>＋ Preparación</button></div><div className="preparation-list">{recognized.map((item,index)=><article key={item.id} className={activePreparationId===item.id?"active":""} onClick={()=>setActivePreparationId(item.id)}><div><span>Preparación {index+1}</span><strong>{item.template?.name||"Productos individuales"}</strong><small>{item.ingredients.map(product=>product.name).join(", ")||"Selecciona ingredientes"}</small></div><b>${item.total.toLocaleString("es-CO")}</b><div className="prep-actions"><button onClick={event=>{event.stopPropagation();duplicatePreparation(item.id)}}>Duplicar</button><button onClick={event=>{event.stopPropagation();removePreparation(item.id)}}>Quitar</button></div></article>)}{Object.entries(individuals).filter(([,quantity])=>quantity>0).map(([id,quantity])=>{const product=products.find(item=>item.id===id);return <div className="individual-line" key={id}><span>{quantity}× {product?.name}</span><b>${(Number(product?.price||0)*quantity).toLocaleString("es-CO")}</b></div>})}</div><div className="cart-total"><span>Total</span><strong>${total.toLocaleString("es-CO")}</strong></div>{error&&<div className="form-alert">{error}</div>}<button className="primary-action" onClick={saveOrder} disabled={saving}>{saving?"Guardando...":editingOrder?"Guardar cambios":"Enviar a cocina"}</button></aside></div>}</Modal>}

  {paymentOrder&&<Modal title={`Cobrar pedido #${paymentOrder.order_number}`} onClose={()=>setPaymentOrder(null)}><div className="payment-summary"><span>Total</span><strong>${Number(paymentOrder.total).toLocaleString("es-CO")}</strong></div><div className="payment-methods">{[["cash","Efectivo"],["card","Tarjeta"],["transfer","Transferencia"],["mixed","Mixto"]].map(([id,label])=><button key={id} className={paymentMode===id?"active":""} onClick={()=>setPaymentMode(id)}>{label}</button>)}</div>{paymentMode==="mixed"&&<div className="payment-parts">{["cash","card","transfer"].map(method=><label key={method}>{({cash:"Efectivo",card:"Tarjeta",transfer:"Transferencia"})[method]}<input type="number" min="0" value={paymentParts[method]} onChange={e=>setPaymentParts({...paymentParts,[method]:e.target.value})}/></label>)}</div>}{error&&<div className="form-alert">{error}</div>}<button className="primary-action order-next" onClick={confirmPayment} disabled={saving}>Confirmar pago</button></Modal>}
  {cancelTarget&&<Modal title={`Cancelar pedido #${cancelTarget.order_number}`} onClose={()=>setCancelTarget(null)}><p>Se liberará la mesa y se devolverán las existencias reservadas.</p><div className="modal-actions"><button className="secondary-button" onClick={()=>setCancelTarget(null)}>Volver</button><button className="danger-button" onClick={confirmCancellation}>Cancelar pedido</button></div></Modal>}
  {refundTarget&&<Modal title={`Devolver pedido #${refundTarget.order_number}`} onClose={()=>setRefundTarget(null)}><label className="standalone-field">Motivo<textarea value={refundReason} onChange={e=>setRefundReason(e.target.value)}/></label><div className="modal-actions"><button className="secondary-button" onClick={()=>setRefundTarget(null)}>Volver</button><button className="danger-button" onClick={confirmRefund}>Confirmar devolución</button></div></Modal>}
 </div>;
}
