import { useState } from "react";
import { useNavigate } from "react-router-dom";
import { createRestaurant } from "../../controllers/authController";

export default function OnboardingPage(){
  const[form,setForm]=useState({businessName:"",restaurantName:"",branchName:"Sede principal",documentType:"NIT",documentNumber:"",verificationDigit:"",billingEmail:"",phone:"",address:"",city:"",currency:"COP",timezone:"America/Bogota"});const[error,setError]=useState("");const[loading,setLoading]=useState(false);const navigate=useNavigate();
  const update=(key,value)=>setForm(current=>({...current,[key]:value}));
  const submit=async(event)=>{event.preventDefault();setLoading(true);setError("");try{await createRestaurant(form);window.location.assign("/dashboard")}catch(failure){setError(failure.message)}finally{setLoading(false)}};
  return <main className="onboarding-shell"><header className="onboarding-header"><div className="auth-brand dark"><span>O</span><strong>Obsidian Mesa</strong></div><div><small>CONFIGURACIÓN INICIAL</small><div className="onboarding-progress"><span style={{width:"100%"}}/></div></div></header><section className="onboarding-card onboarding-wide"><span className="auth-kicker">DATOS DEL RESTAURANTE</span><h1>Prepara la información de tus documentos</h1><p>Estos datos identificarán el restaurante en comprobantes e informes. Podrás actualizarlos en Configuración.</p><form className="onboarding-form" onSubmit={submit}><div className="form-columns"><label>Razón social o nombre de la empresa<input value={form.businessName} onChange={event=>update("businessName",event.target.value)} required/></label><label>Nombre comercial del restaurante<input value={form.restaurantName} onChange={event=>update("restaurantName",event.target.value)} required/></label></div><div className="document-columns"><label>Tipo de documento<select value={form.documentType} onChange={event=>update("documentType",event.target.value)}><option>NIT</option><option>CC</option><option>CE</option><option>PASAPORTE</option></select></label><label>Número de documento<input value={form.documentNumber} onChange={event=>update("documentNumber",event.target.value)} required/></label><label>Dígito de verificación<input value={form.verificationDigit} onChange={event=>update("verificationDigit",event.target.value)} maxLength="1" placeholder="Opcional"/></label></div><div className="form-columns"><label>Correo del restaurante<input type="email" value={form.billingEmail} onChange={event=>update("billingEmail",event.target.value)} required/></label><label>Teléfono<input type="tel" value={form.phone} onChange={event=>update("phone",event.target.value)} required/></label></div><label>Dirección principal<input value={form.address} onChange={event=>update("address",event.target.value)} required/></label><div className="form-columns"><label>Ciudad<input value={form.city} onChange={event=>update("city",event.target.value)} required/></label><label>Primera sede<input value={form.branchName} onChange={event=>update("branchName",event.target.value)} required/></label></div><div className="info-note"><span>i</span><p><strong>¿Aún no tienes NIT?</strong> Puedes registrar el documento del propietario y actualizarlo después.</p></div>{error&&<div className="form-alert">{error}</div>}<button className="auth-submit" disabled={loading}>{loading?"Preparando tu restaurante...":"Crear mi restaurante"}<span>→</span></button></form></section></main>;
}
