import {useEffect,useMemo,useState} from "react";
import PageHeader from "../../components/PageHeader";
import LoadingState from "../../components/LoadingState";
import Modal from "../../components/Modal";
import {getPlans,getSaasSubscriptions,updateSaasSubscription} from "../../controllers/subscriptionController";
import {useAuth} from "../../context/AuthContext";

const states={trialing:"Prueba",active:"Activa",past_due:"Pago pendiente",grace_period:"Gracia",suspended:"Suspendida",cancelled:"Cancelada",archived:"Archivada"};
const fmt=value=>value?new Intl.DateTimeFormat("es-CO",{dateStyle:"medium"}).format(new Date(value)):"—";
const dateInput=value=>value?new Date(value).toISOString().slice(0,10):"";
export default function SaasAdminPage(){
 const{isPlatformAdmin}=useAuth();const[items,setItems]=useState([]),[plans,setPlans]=useState([]),[editing,setEditing]=useState(null),[search,setSearch]=useState(""),[loading,setLoading]=useState(true),[error,setError]=useState("");
 const load=()=>Promise.all([getSaasSubscriptions(),getPlans()]).then(([a,b])=>{setItems(a);setPlans(b);setError("")}).catch(e=>setError(e.message)).finally(()=>setLoading(false));useEffect(()=>{if(isPlatformAdmin)load();else setLoading(false)},[isPlatformAdmin]);
 const filtered=useMemo(()=>items.filter(i=>`${i.tenants?.business_name} ${i.tenants?.billing_email}`.toLowerCase().includes(search.toLowerCase())),[items,search]);
 const metrics={total:items.length,trial:items.filter(i=>i.status==="trialing").length,active:items.filter(i=>i.status==="active").length,attention:items.filter(i=>["past_due","grace_period","suspended"].includes(i.status)).length};
 const save=async e=>{e.preventDefault();const f=new FormData(e.currentTarget);try{await updateSaasSubscription(editing.id,{status:f.get("status"),planId:f.get("planId"),trialEndsAt:f.get("trialEndsAt")||null,currentPeriodEndsAt:f.get("periodEndsAt")||null,graceEndsAt:f.get("graceEndsAt")||null,overrides:{mobile_concurrent_sessions:Number(f.get("mobile")),registered_users:Number(f.get("users")),branches:Number(f.get("branches"))}});setEditing(null);load()}catch(err){setError(err.message)}};
 if(!isPlatformAdmin)return <div className="content"><PageHeader eyebrow="PLATAFORMA" title="Acceso restringido" description="Esta sección es exclusiva para administradores autorizados del SaaS."/></div>;
 if(loading)return <div className="content"><LoadingState label="Cargando clientes"/></div>;
 return <div className="content"><PageHeader eyebrow="PLATAFORMA" title="Administración SaaS" description="Gestiona clientes, vigencias y límites contratados."/>{error&&<div className="form-alert module-alert">{error}</div>}
  <section className="saas-metrics">{[["Restaurantes",metrics.total],["En prueba",metrics.trial],["Activos",metrics.active],["Requieren atención",metrics.attention]].map(([a,b])=><article className="surface-card" key={a}><span>{a}</span><strong>{b}</strong></article>)}</section>
  <div className="module-toolbar"><input className="search-input" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Buscar restaurante o correo"/><button className="secondary-button" onClick={load}>Actualizar</button></div>
  <section className="surface-card saas-table"><div className="saas-row saas-labels"><span>Restaurante</span><span>Plan</span><span>Estado</span><span>Vencimiento</span><span>Límite móvil</span><span/></div>{filtered.map(item=>{const limits={...item.plans?.limits,...item.overrides};const expiration=item.status==="trialing"?item.trial_ends_at:item.current_period_ends_at||item.trial_ends_at;return <article className="saas-row" key={item.id}><span><strong>{item.tenants?.business_name}</strong><small>{item.tenants?.billing_email||"Sin correo"}</small></span><span>{item.plans?.name}</span><span><i className={`subscription-status ${item.status}`}>{states[item.status]}</i></span><span>{fmt(expiration)}</span><span>{limits.mobile_concurrent_sessions||0} apps</span><button className="secondary-button" onClick={()=>setEditing(item)}>Administrar</button></article>})}</section>
  {editing&&<Modal title={`Suscripción · ${editing.tenants?.business_name}`} onClose={()=>setEditing(null)}><form className="module-form subscription-form" onSubmit={save}><label>Estado<select name="status" defaultValue={editing.status}>{Object.entries(states).map(([v,l])=><option value={v} key={v}>{l}</option>)}</select></label><label>Plan<select name="planId" defaultValue={editing.plan_id}>{plans.map(p=><option value={p.id} key={p.id}>{p.name}</option>)}</select></label><div className="form-columns"><label>Fin de prueba<input type="date" name="trialEndsAt" defaultValue={dateInput(editing.trial_ends_at)}/></label><label>Fin del periodo<input type="date" name="periodEndsAt" defaultValue={dateInput(editing.current_period_ends_at)}/></label></div><label>Fin del periodo de gracia<input type="date" name="graceEndsAt" defaultValue={dateInput(editing.grace_ends_at)}/></label><h3>Límites particulares</h3><div className="form-columns"><label>Apps móviles<input type="number" min="0" name="mobile" defaultValue={editing.overrides?.mobile_concurrent_sessions??editing.plans?.limits?.mobile_concurrent_sessions??2}/></label><label>Usuarios registrados<input type="number" min="0" name="users" defaultValue={editing.overrides?.registered_users??editing.plans?.limits?.registered_users??10}/></label></div><label>Sedes<input type="number" min="0" name="branches" defaultValue={editing.overrides?.branches??editing.plans?.limits?.branches??1}/></label><button className="primary-action">Guardar cambios</button></form></Modal>}
 </div>;
}
