import{useEffect,useMemo,useState}from"react";
import PageHeader from"../../components/PageHeader";
import LoadingState from"../../components/LoadingState";
import EmptyState from"../../components/EmptyState";
import Modal from"../../components/Modal";
import{getCatalog,getInventory,updateInventory}from"../../controllers/operationsController";
import{getRestaurantProfile}from"../../controllers/authController";
import{downloadInventoryExcel,downloadInventoryPdf}from"../../utils/reportExport";

const today=()=>new Intl.DateTimeFormat("en-CA",{timeZone:"America/Bogota",year:"numeric",month:"2-digit",day:"2-digit"}).format(new Date());
export default function InventoryPage(){
 const[products,setProducts]=useState([]),[categories,setCategories]=useState([]),[profile,setProfile]=useState(null),[category,setCategory]=useState("all"),[search,setSearch]=useState(""),[loading,setLoading]=useState(true),[error,setError]=useState(""),[message,setMessage]=useState(""),[exporting,setExporting]=useState(""),[editing,setEditing]=useState(null),[mode,setMode]=useState("add"),[quantity,setQuantity]=useState("");
 const load=()=>{setLoading(true);setError("");return Promise.all([getCatalog(),getInventory(),getRestaurantProfile()]).then(([catalog,inventory,restaurant])=>{setCategories((catalog.categories||[]).filter(item=>item.is_active));setProducts(inventory||[]);setProfile(restaurant)}).catch(f=>setError(f.message)).finally(()=>setLoading(false))};useEffect(()=>{load()},[]);
 const rows=useMemo(()=>products.map(product=>{const remaining=product.inventory?.quantity??null,unlimited=remaining===null,status=unlimited?"unlimited":remaining===0?"sold_out":remaining<=5?"low":"available";return{id:product.id,name:product.name,categoryId:product.category_id,category:product.product_categories?.name||"Sin categoría",remaining,initial:remaining,initialLabel:remaining===null?"Sin control":String(remaining),remainingLabel:remaining===null?"Sin control":String(remaining),status,statusLabel:{unlimited:"Sin control",sold_out:"Agotado",low:"Pocas unidades",available:"Disponible"}[status]}}).filter(row=>(category==="all"||row.categoryId===category)&&row.name.toLowerCase().includes(search.toLowerCase())),[products,category,search]);
 const totals={controlled:rows.filter(row=>row.remaining!==null).length,low:rows.filter(row=>row.status==="low").length,sold:rows.filter(row=>row.status==="sold_out").length};
 const exportFile=async type=>{setExporting(type);try{const payload={rows,profile,date:today()};if(type==="pdf")await downloadInventoryPdf(payload);else await downloadInventoryExcel(payload)}catch(f){setError(f.message)}finally{setExporting("")}};
 const openEntry=row=>{setEditing(row);setMode(row.remaining===null?"set":"add");setQuantity("");setError("")};
 const save=async event=>{event.preventDefault();try{setError("");const result=await updateInventory(editing.id,{mode,quantity:Number(quantity)});setMessage(result.message);setEditing(null);await load()}catch(f){setError(f.message)}};
 if(loading)return <div className="content"><PageHeader eyebrow="OPERACIÓN" title="Inventario"/><section className="surface-card"><LoadingState label="Consultando inventario permanente..."/></section></div>;
 return <div className="content"><PageHeader eyebrow="OPERACIÓN" title="Inventario" description="Las existencias permanecen entre días y se descuentan con cada pedido." action={<div className="report-export-actions"><button className="secondary-button" onClick={()=>exportFile("excel")} disabled={Boolean(exporting)}>{exporting==="excel"?"Generando...":"Descargar Excel"}</button><button className="secondary-button" onClick={()=>exportFile("pdf")} disabled={Boolean(exporting)}>{exporting==="pdf"?"Generando...":"Descargar PDF"}</button></div>}/>{error&&!editing&&<div className="form-alert module-alert">{error}</div>}{message&&<div className="success-alert module-alert">✓ {message}</div>}
  <section className="inventory-metrics"><article><span>Productos controlados</span><strong>{totals.controlled}</strong></article><article><span>Pocas unidades</span><strong>{totals.low}</strong></article><article><span>Agotados</span><strong>{totals.sold}</strong></article></section>
  <div className="inventory-toolbar"><div className="segmented inventory-categories"><button className={category==="all"?"active":""} onClick={()=>setCategory("all")}>Todos</button>{categories.map(item=><button className={category===item.id?"active":""} onClick={()=>setCategory(item.id)} key={item.id}>{item.name}</button>)}</div><input className="search-input" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Buscar producto..."/><span/></div>
  <section className="surface-card inventory-table">{rows.length?<><div className="inventory-row inventory-labels"><span>Producto</span><span>Categoría</span><span>Existencia actual</span><span>Estado</span><span>Acción</span></div>{rows.map(row=><article className="inventory-row" key={row.id}><span><strong>{row.name}</strong></span><span>{row.category}</span><span><b>{row.remainingLabel}</b></span><span><i className={`inventory-status ${row.status}`}>{row.statusLabel}</i></span><span><button className="secondary-button inventory-entry-button" onClick={()=>openEntry(row)}>Ingresar / ajustar</button></span></article>)}</>:<EmptyState icon="IV" title="No hay productos para mostrar" description="Cambia los filtros o crea productos en el menú."/>}</section>
  {editing&&<Modal title={`Inventario: ${editing.name}`} description={`Existencia actual: ${editing.remainingLabel}`} onClose={()=>setEditing(null)}><form className="module-form" onSubmit={save}><div className="payment-methods"><button type="button" className={mode==="add"?"active":""} onClick={()=>setMode("add")}>Sumar reposición</button><button type="button" className={mode==="set"?"active":""} onClick={()=>setMode("set")}>Fijar cantidad real</button></div><label>{mode==="add"?"Unidades que ingresan":"Cantidad contada"}<input autoFocus type="number" min="0" step="1" value={quantity} onChange={e=>setQuantity(e.target.value)} required/></label><small>{mode==="add"?"Se sumarán al saldo existente.":"Reemplazará el saldo actual después de un conteo físico."}</small>{error&&<div className="form-alert">{error}</div>}<button className="primary-action">Guardar inventario</button></form></Modal>}
 </div>;
}
