import{useEffect,useMemo,useState}from"react";
import PageHeader from"../../components/PageHeader";
import LoadingState from"../../components/LoadingState";
import EmptyState from"../../components/EmptyState";
import{getCatalog,getDailyMenu}from"../../controllers/operationsController";
import{getRestaurantProfile}from"../../controllers/authController";
import{downloadInventoryExcel,downloadInventoryPdf}from"../../utils/reportExport";

const today=()=>new Intl.DateTimeFormat("en-CA",{timeZone:"America/Bogota",year:"numeric",month:"2-digit",day:"2-digit"}).format(new Date());
export default function InventoryPage(){
 const[date,setDate]=useState(today()),[products,setProducts]=useState([]),[categories,setCategories]=useState([]),[menu,setMenu]=useState(null),[profile,setProfile]=useState(null),[category,setCategory]=useState("all"),[search,setSearch]=useState(""),[loading,setLoading]=useState(true),[error,setError]=useState(""),[exporting,setExporting]=useState("");
 const load=()=>{setLoading(true);setError("");Promise.all([getCatalog(),getDailyMenu(date),getRestaurantProfile()]).then(([catalog,daily,restaurant])=>{setProducts(catalog.products||[]);setCategories((catalog.categories||[]).filter(item=>item.is_active));setMenu(daily.menu);setProfile(restaurant)}).catch(f=>setError(f.message)).finally(()=>setLoading(false))};useEffect(()=>{load()},[date]);
 const rows=useMemo(()=>{const direct=new Map((menu?.daily_menu_items||[]).map(item=>[item.product_id,item])),optionStock=new Map((menu?.daily_menu_option_stocks||[]).map(item=>[item.option_id,item])),componentSources=new Map();for(const owner of products)for(const group of owner.product_option_groups||[])for(const option of group.product_options||[]){const stock=optionStock.get(option.id);if(!stock)continue;const list=componentSources.get(option.component_product_id)||[];list.push(stock);componentSources.set(option.component_product_id,list)}
  return products.filter(product=>product.is_active&&product.product_type!=="composite").map(product=>{const item=direct.get(product.id),sources=componentSources.get(product.id)||[];let initial=item?.stock_quantity??null,remaining=item?.remaining_quantity??null;if(!item&&sources.length){const controlled=sources.filter(source=>source.stock_quantity!==null);if(controlled.length){initial=controlled.reduce((sum,source)=>sum+Number(source.stock_quantity),0);remaining=controlled.reduce((sum,source)=>sum+Number(source.remaining_quantity),0)}}const unlimited=remaining===null,status=unlimited?"unlimited":remaining===0?"sold_out":remaining<=5?"low":"available";return{id:product.id,name:product.name,categoryId:product.category_id,category:product.product_categories?.name||"Sin categoría",initial,remaining,initialLabel:initial===null?"Sin límite":String(initial),remainingLabel:remaining===null?"Sin límite":String(remaining),status,statusLabel:{unlimited:"Sin límite",sold_out:"Agotado",low:"Pocas unidades",available:"Disponible"}[status]}}).filter(row=>(category==="all"||row.categoryId===category)&&row.name.toLowerCase().includes(search.toLowerCase()))},[products,menu,category,search]);
 const totals={controlled:rows.filter(row=>row.remaining!==null).length,low:rows.filter(row=>row.status==="low").length,sold:rows.filter(row=>row.status==="sold_out").length};
 const exportFile=async type=>{setExporting(type);try{const payload={rows,profile,date};if(type==="pdf")await downloadInventoryPdf(payload);else await downloadInventoryExcel(payload)}catch(f){setError(f.message)}finally{setExporting("")}};
 if(loading)return <div className="content"><PageHeader eyebrow="OPERACIÓN" title="Inventario"/><section className="surface-card"><LoadingState label="Consultando existencias del día..."/></section></div>;
 return <div className="content"><PageHeader eyebrow="OPERACIÓN" title="Inventario del día" description="Consulta las existencias disponibles de los productos publicados." action={<div className="report-export-actions"><button className="secondary-button" onClick={()=>exportFile("excel")} disabled={Boolean(exporting)}>{exporting==="excel"?"Generando...":"Descargar Excel"}</button><button className="secondary-button" onClick={()=>exportFile("pdf")} disabled={Boolean(exporting)}>{exporting==="pdf"?"Generando...":"Descargar PDF"}</button></div>}/>{error&&<div className="form-alert module-alert">{error}</div>}
  <section className="inventory-metrics"><article><span>Productos controlados</span><strong>{totals.controlled}</strong></article><article><span>Pocas unidades</span><strong>{totals.low}</strong></article><article><span>Agotados</span><strong>{totals.sold}</strong></article></section>
  <div className="inventory-toolbar"><div className="segmented inventory-categories"><button className={category==="all"?"active":""} onClick={()=>setCategory("all")}>Todos</button>{categories.map(item=><button className={category===item.id?"active":""} onClick={()=>setCategory(item.id)} key={item.id}>{item.name}</button>)}</div><input className="search-input" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Buscar producto..."/><label>Fecha<input type="date" value={date} onChange={e=>setDate(e.target.value)}/></label></div>
  <section className="surface-card inventory-table">{rows.length?<><div className="inventory-row inventory-labels"><span>Producto</span><span>Categoría</span><span>Inicial</span><span>Disponible</span><span>Estado</span></div>{rows.map(row=><article className="inventory-row" key={row.id}><span><strong>{row.name}</strong></span><span>{row.category}</span><span>{row.initialLabel}</span><span><b>{row.remainingLabel}</b></span><span><i className={`inventory-status ${row.status}`}>{row.statusLabel}</i></span></article>)}</>:<EmptyState icon="IV" title="No hay productos para mostrar" description="Cambia los filtros o publica el menú de esta fecha."/>}</section>
 </div>;
}
